#!/usr/bin/env bash

# script to submit Schrödinger commands using filename from "queue.txt"
# only submits new jobs when current joblist is shorter than a threshold
# execute this script frequently through cronjob to use it as queueing system
# example crontab
# * * * * * cd /path/to/log_out_dir && /path/to/queueligprep

SCHRODINGER=/opt/schrodinger/suites2023-2
WORKDIR=/Users/julian/SciAdv\ revisions
nJobs=$("$SCHRODINGER/jobcontrol" -list | wc -l) || exit 1

if [ "$nJobs" -lt 34 ]
then
    for ((i=0; i<2; i++))
    do

        nextFile=$(head -1 "$WORKDIR/queue.txt")  || exit 1
        $SCHRODINGER/ligprep -icsv "$WORKDIR/Data_S4/${nextFile}_smiles.csv" -omae "$WORKDIR/ligprep_out/$nextFile.mae" || exit 1
        tail -n +2 "$WORKDIR/queue.txt" > temp && mv temp "$WORKDIR/queue.txt";
    done
fi

