#!/usr/bin/env bash

# monitor if websites are up
# receive an email if they do not respond 200
# intended to be run as a cronjob
# example crontab to run every 30 min:
# */30 * * * * cd /path/to/this/directory && ./monitorsites.sh

SITESFILE=sites.txt # list the sites you want to monitor in this file (one per line)
EMAILS="yourname@example.com" # list of email addresses to receive alerts (comma separated)

while read site; do
    if [ ! -z "${site}" ]; then
        
        CURL=$(curl -s --head $site)
        
        if echo $CURL | grep "200 OK" > /dev/null
        then
            echo "The HTTP server on ${site} is up!"
        else    

            MESSAGE="This is an alert that your site ${site} has failed to respond 200 OK.
This alert is generated by script ${0##*/} running on $(hostname)"

            for EMAIL in $(echo $EMAILS | tr "," " "); do
                SUBJECT="WebAdmin alert: $site Failed to respond 200 OK"
                echo "$MESSAGE" | mail -s "$SUBJECT" $EMAIL
                echo $SUBJECT
                echo "Alert sent to $EMAIL"
            done      
        fi
    fi
done < $SITESFILE

